name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt' # Ajout de la distribution Java requise.
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ secrets.ACTOR }}
          server-password: ${{ secrets.PASSWORD }}
          overwrite-settings: true
          job-status: success
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
