name: Android Build and Email

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: path/to/your/app-release.apk

  send-email:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: app-release.apk

    - name: Send Email with APK
      run: |
        echo "Sending email with APK..."
        # Utilisez ici votre script ou action pour envoyer l'email
